In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
data =  pd.read_csv('/content/drive/MyDrive/Introduction to AI_2025-26/Lab_2026/Lab1/diamonds.csv')

In [ ]:
data

       carat        cut color clarity  depth  table     x     y     z  price
0       0.23      Ideal     E     SI2   61.5   55.0  3.95  3.98  2.43    326
1       0.21    Premium     E     SI1   59.8   61.0  3.89  3.84  2.31    326
2       0.23       Good     E     VS1   56.9   65.0  4.05  4.07  2.31    327
3       0.29    Premium     I     VS2   62.4   58.0  4.20  4.23  2.63    334
4       0.31       Good     J     SI2   63.3   58.0  4.34  4.35  2.75    335
...      ...        ...   ...     ...    ...    ...   ...   ...   ...    ...
53935   0.72      Ideal     D     SI1   60.8   57.0  5.75  5.76  3.50   2757
53936   0.72       Good     D     SI1   63.1   55.0  5.69  5.75  3.61   2757
53937   0.70  Very Good     D     SI1   62.8   60.0  5.66  5.68  3.56   2757
53938   0.86    Premium     H     SI2   61.0   58.0  6.15  6.12  3.74   2757
53939   0.75      Ideal     D     SI2   62.2   55.0  5.83  5.87  3.64   2757

[53940 rows x 10 columns]

## **Lab1: Introduction to Python**
* Loops in Python
* In built Data Structures in Python
* Functions in Python
* Data loading & cleaning
* Statistical profiling (NumPy & Pandas)

# **1. Loops in Python**
* `for` loop
* `while` loop

## **1.1 `for` loop demonstartion**
### **1.1.1 Example 1 – Print first 5 diamond prices**

In [ ]:
for i in range(5):
  print(f'Diamond, {i+1}, Price : {data['price'][i]}')
  print("Diamond:", i+1, "Price:", data['price'][i])

Diamond, 1, Price : 326
Diamond: 1 Price: 326
Diamond, 2, Price : 326
Diamond: 2 Price: 326
Diamond, 3, Price : 327
Diamond: 3 Price: 327
Diamond, 4, Price : 334
Diamond: 4 Price: 334
Diamond, 5, Price : 335
Diamond: 5 Price: 335

### **1.1.2 Example 2 – Display carat & cut of first 10 diamonds**

In [ ]:
for i in range(10):
  carat = data["carat"][i]
  cut = data["cut"][i]
  print("Diamond:", i+1, "Carat:", carat, "Cut:", cut)

Diamond: 1 Carat: 0.23 Cut: Ideal
Diamond: 2 Carat: 0.21 Cut: Premium
Diamond: 3 Carat: 0.23 Cut: Good
Diamond: 4 Carat: 0.29 Cut: Premium
Diamond: 5 Carat: 0.31 Cut: Good
Diamond: 6 Carat: 0.24 Cut: Very Good
Diamond: 7 Carat: 0.24 Cut: Very Good
Diamond: 8 Carat: 0.26 Cut: Very Good
Diamond: 9 Carat: 0.22 Cut: Fair
Diamond: 10 Carat: 0.23 Cut: Very Good

### **1.1.3 Example 3 – Count how many diamonds have carat > 1**

In [ ]:
count = 0

for i in data['carat']:
  if i > 1:
    count +=1

print("Count of diamonds with carat > 1:", count)

Count of diamonds with carat > 1: 17502

## **1.2 `while` loop demonstration**

### **1.2.1 Example 4 – Print diamonds until price exceeds 20,000**

In [ ]:
i = 0
while i < len(data) and data['price'][i] <=20000:
  print("Diamond:", i+1, "Price:", data['price'])
  i +=1

Streaming output truncated to the last 5000 lines.
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53525 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53526 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53527 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53528 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53529 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53530 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53531 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53532 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53533 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53534 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53535 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53536 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53537 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53538 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53539 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53540 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53541 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53542 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53543 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53544 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53545 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53546 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53547 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53548 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53549 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53550 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53551 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53552 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53553 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53554 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53555 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53556 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53557 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53558 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53559 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53560 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53561 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53562 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53563 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53564 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53565 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53566 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53567 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53568 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53569 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53570 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53571 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53572 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53573 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53574 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53575 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53576 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53577 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53578 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53579 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53580 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53581 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53582 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53583 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53584 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53585 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53586 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53587 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53588 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53589 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53590 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53591 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53592 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53593 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53594 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53595 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53596 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53597 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53598 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53599 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53600 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53601 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53602 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53603 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53604 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53605 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53606 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53607 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53608 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53609 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53610 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53611 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53612 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53613 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53614 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53615 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757
53938    2757
53939    2757
Name: price, Length: 53940, dtype: int64
Diamond: 53616 Price: 0         326
1         326
2         327
3         334
4         335
         ...
53935    2757
53936    2757
53937    2757

### **1.2.2 Example 5 – Sum prices of first 15 diamonds**

In [ ]:
i = 0
total_price = 0

while i < 15:
  total_price += data['price'][i]
  i += 1
print("Total price of first 15 diamonds :", total_price)

Total price of first 15 diamonds : 5042

# **2. In-built Data Structures in Python**
## **2.1 LISTS Demonstration**

### **2.1.1 Create a list of first 10 diamond prices**

In [ ]:
price_list = list(data['price'].head(10))
print("Price List", price_list)

Price List [326, 326, 327, 334, 335, 336, 336, 337, 337, 338]

### **2.1.2 Find maximum and minimum price using list**

In [ ]:
print("Maximum Price :", max(price_list))
print("Minimum Price :", min(price_list))

Maximum Price : 338
Minimum Price : 326

## **2.2 TUPLE Demonstration**

### **2.2.1 Store first 5 diamonds (carat, cut) as tuple**

In [ ]:
diamond_tuple = tuple(zip(data['carat'].head(5), data['cut'].head(5)))
print("Diamond Tuple:", diamond_tuple)

Diamond Tuple: ((0.23, 'Ideal'), (0.21, 'Premium'), (0.23, 'Good'), (0.29, 'Premium'), (0.31, 'Good'))

## **2.3 DICTIONARY Demonstartion**

### **2.3.1 Create a dictionary of diamond index and price**

In [ ]:
price_dict = {}
for i in range(10):
    price_dict[i] = data["price"][i]

print("Price Dictionary:", price_dict)

Price Dictionary: {0: np.int64(326), 1: np.int64(326), 2: np.int64(327), 3: np.int64(334), 4: np.int64(335), 5: np.int64(336), 6: np.int64(336), 7: np.int64(337), 8: np.int64(337), 9: np.int64(338)}

## **2.3.2 Dictionary with carat as key and cut as value**

In [ ]:
carat_cut_dict = {}

for i in range(5):
    carat_cut_dict[data["carat"][i]] = data["cut"][i]

print("Carat–Cut Dictionary:", carat_cut_dict)

Carat–Cut Dictionary: {np.float64(0.23): 'Good', np.float64(0.21): 'Premium', np.float64(0.29): 'Premium', np.float64(0.31): 'Good'}

### **2.3.3 Mini Real-Life Use Case**

In [ ]:
category = {"Low":[], "Medium":[], "High":[]}

for p in data["price"].head(20):
    if p < 3000:
        category["Low"].append(p)
    elif p <= 7000:
        category["Medium"].append(p)
    else:
        category["High"].append(p)

print(category)

{'Low': [326, 326, 327, 334, 335, 336, 336, 337, 337, 338, 339, 340, 342, 344, 345, 345, 348, 351, 351, 351], 'Medium': [], 'High': []}

# **3. NumPy**
NumPy (Numerical Python) is an open source Python library that’s widely used in science and engineering. The NumPy library contains multidimensional array data structures, such as the homogeneous, N-dimensional ndarray, and a large library of functions that operate efficiently on these data structures.

In [ ]:
#Installation
!pip install numpy

In [ ]:
# Importing
import numpy as np

# Creating an Arrays using NumPy
## Creating 1D array
arr1 = np.array([1,2,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 2 3 4 5]
<class 'numpy.ndarray'>
(6,)

In [ ]:
# Reshape Column Array to Row array
arr1.reshape((6,1))

array([[1],
       [2],
       [2],
       [3],
       [4],
       [5]])

In [ ]:
# Reshaping !D to 2D Array
a1 = np.array([2,3,4,5,6,7,8,9])
a1.reshape((2,4))

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

### **3.1`arange()` function**

In [ ]:
np.arange(1,11,2) #range, step

array([1, 3, 5, 7, 9])

In [ ]:
# Reshaping
np.arange(1,16).reshape((3,5))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
# initializing values with zero
np.zeros((1,6)).reshape(3,2)

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
# With ones
np.ones((2,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

### **3.2 Method to create an `Identity Matrix`**

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
arr = np.array([[1,2,3,4], [5,6,7,8]])

print(f'Array:\n{arr}\n')
print(f'Shape:{arr.shape}\n') # Output : (2,4)
print(f'Number of Dimension:{arr.ndim}\n') # Output : 2
print(f'Size (Number of Elements) : {arr.size}\n') # Output: 8
print(f'Data Type : {arr.dtype}\n') # Output : int32
print(f'Item Size (in Bytes): {arr.itemsize}') # Output : 8 (may vary based on the platform)
#

Array:
[[1 2 3 4]
 [5 6 7 8]]

Shape:(2, 4)

Number of Dimension:2

Size (Number of Elements) : 8

Data Type : int64

Item Size (in Bytes): 8

In [ ]:
a_square = np.square(arr)
print(a_square)

[[ 1  4  9 16]
 [25 36 49 64]]

In [ ]:
a_exp = np.exp(arr)
print(a_exp)

[[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01]
 [1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03]]

## **3.3 Adding, Sorting, and COncatenation**

In [ ]:
# Addition
a = np.array([2,4,5,6,1,22,10])
b = np.array([8,5,6,2,3,11,78])
a + b

array([10,  9, 11,  8,  4, 33, 88])

## **3.4 np.sort() : Sorts the elements of an array**

In [ ]:
# Sorting ascending
np.sort(a)

array([ 1,  2,  4,  5,  6, 10, 22])

In [ ]:
scores = np.array([72, 88, 65, 91, 80])

desc_sorted = np.sort(scores)[::-1]

print("Descending order:", desc_sorted)

Descending order: [91 88 80 72 65]

## **3.5 np.concatenate: Joins arrays along an existing axis**

In [ ]:
# Concatenation
np.concatenate((a,b))

array([ 2,  4,  5,  6,  1, 22, 10,  8,  5,  6,  2,  3, 11, 78])

In [ ]:
a1 = np.array([[1,2,3], [4,5,6]])
b1 = np.array([[7,8,9], [10,11,12]])
np.concatenate((a1,b1), axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

### **3.6 2D Array Example (Row-wise descending sort)**

In [ ]:
data = np.array([[3, 7, 1],
                 [8, 4, 6]])

desc_sorted_rows = np.sort(data, axis=1)[:, ::-1]
print(desc_sorted_rows)

[[7 3 1]
 [8 6 4]]

### **3.7 Column-wise descending sort**

In [ ]:
data = np.array([[3, 7, 1],
                 [8, 4, 6]])

desc_sorted_cols = np.sort(data, axis=0)[::-1, :]
print(desc_sorted_cols)

[[8 7 6]
 [3 4 1]]

## **3.8 np.hstack() : Stacks arrays horizontally**

In [ ]:
np.hstack((a1,b1))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

## **3.9 np.vstack(): Stacks arrays vertically**

In [ ]:
np.vstack((a1,b1))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
x_dot = np.dot(a1,b1)# Mismatch of matrix dimension
print(x_dot)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [ ]:
x_dot = np.dot(a1,b1.T)
print(x_dot)

[[ 50  68]
 [122 167]]

In [ ]:
np.min(a1)

np.int64(1)

In [ ]:
np.ravel(a1)

array([1, 2, 3, 4, 5, 6])

In [ ]:
scores = np.array([88, 92, 79, 95, 85])

min_index = np.argmin(scores)

print("Scores:", scores)
print("Index of minimum value:", min_index)
print("Minimum value:", scores[min_index])

Scores: [88 92 79 95 85]
Index of minimum value: 2
Minimum value: 79

In [ ]:
## 2-D array
marks = np.array([[85, 90, 88],
                  [78, 92, 80]])

min_pos = np.argmin(marks)
row, col = np.unravel_index(min_pos, marks.shape)

print("Minimum value:", marks[row, col])
print("Located at row", row, "column", col)

Minimum value: 78
Located at row 1 column 0

### **3.10 np.where(): Selecting Values That Satisfy a Condition**

In [ ]:
# np.where()
marks = np.array([35, 68, 72, 41, 90, 28])

passed = np.where(marks >= 40)

print("Indices of students who passed:", passed)
print("Marks of students who passed:", marks[passed])

Indices of students who passed: (array([1, 2, 3, 4]),)
Marks of students who passed: [68 72 41 90]

## **3.11 np.linspace(): Generating Evenly Spaced Numbers**
* This function is commonly used for generating smooth numeric ranges for plotting and numerical experiments.

In [ ]:
values = np.linspace(0, 10, 6) # 0: starting value, 10: ending value, 6:is the total number of evenly spaced values (including both endpoints
print("Generated values:", values)

Generated values: [ 0.  2.  4.  6.  8. 10.]

## **3.11 NumPy Operations on csv file**

In [ ]:
# reading file
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/Introduction to AI_2025-26/Lab_2026/Lab1/diamonds.csv')

### **3.11.1. np.mean() — Average Diamond Price**

In [ ]:
avg_price = np.mean(df["price"].values)
print("Average Price:", avg_price)

Average Price: 3932.799721913237

### **3.11.2. np.min() and np.max() — Price Range**

In [ ]:
min_price = np.min(df["price"].values)
max_price = np.max(df["price"].values)

print("Minimum Price:", min_price)
print("Maximum Price:", max_price)

Minimum Price: 326
Maximum Price: 18823

### **3.11.3. np.argmax() — Most Expensive Diamond**

In [ ]:
idx = np.argmax(df["price"].values)
print("Most expensive diamond:\n", df.iloc[idx])

Most expensive diamond:
 carat         2.29
cut        Premium
color            I
clarity        VS2
depth         60.8
table         60.0
x              8.5
y             8.47
z             5.16
price        18823
Name: 27749, dtype: object

### **3.11.4. np.argmin() — Cheapest Diamond**

In [ ]:
idx = np.argmin(df["price"].values)
print("Cheapest diamond:\n", df.iloc[idx])

Cheapest diamond:
 carat       0.23
cut        Ideal
color          E
clarity      SI2
depth       61.5
table       55.0
x           3.95
y           3.98
z           2.43
price        326
Name: 0, dtype: object

### **3.11.5. np.where() — Diamonds Above ₹10,000**

In [ ]:
expensive_idx = np.where(df["price"].values > 10000)
df.loc[expensive_idx].head()

       carat        cut color clarity  depth  table     x     y     z  price
21928   1.70      Ideal     J     VS2   60.5   58.0  7.73  7.74  4.68  10002
21929   1.03      Ideal     E    VVS2   60.6   59.0  6.50  6.53  3.95  10003
21930   1.23  Very Good     G    VVS2   60.6   55.0  6.93  7.02  4.23  10004
21931   1.25      Ideal     F     VS2   61.6   55.0  6.93  6.96  4.28  10006
21932   2.01  Very Good     I     SI2   61.4   63.0  8.19  7.96  4.96  10009

### **3.11.6. np.sort() — Top 10 Most Expensive Diamonds**

In [ ]:
top_prices = np.sort(df["price"].values)[-10:][::-1]
print("Top 10 Prices:", top_prices)

Top 10 Prices: [18823 18818 18806 18804 18803 18797 18795 18795 18791 18791]

### **3.11.7. np.unique() — Unique Cut Types**

In [ ]:
cuts = np.unique(df["cut"].values)
print("Cut Types:", cuts)

Cut Types: ['Fair' 'Good' 'Ideal' 'Premium' 'Very Good']

# **4. Pandas**
* Padas is a powerful data manipulation library in Python, widely used for data analysis and data cleaning.
* It provides two primary data structures: **Series** and **DataFrame**.
* `series` is a one-dimensional array-like object, while `DataFrame` is a 2-dimensional, size mutable, and potentially heterogeneous tabular data structure with labeled axes(rows and columns)

## **4.1 Installing and Importing libraries**

In [ ]:
# Installing
!pip install pandas

Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.4.9)
Requirement already satisfied: numpy>=1.23 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Requirement already satisfied: seaborn in /usr/local/lib/python3.12/dist-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /usr/local/lib/python3.12/dist-packages (from seaborn) (2.0.2)
Requirement already satisfied: pandas>=1.2 in /usr/local/lib/python3.12/dist-packages (from seaborn) (2.2.2)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /usr/local/lib/python3.12/dist-packages (from seaborn) (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (25.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2->seaborn) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)

In [ ]:
# Importing Library
import pandas as pd

## **4.2 Series**

In [ ]:
# Create series
a = [1,2,3,4,5,6,7,8,9]
print(f'Data type : {type(a)}')
print(a)
a_series = pd.Series(a)
print(f'Data type : {type(a_series)}')
print(a_series)

Data type : <class 'list'>
[1, 2, 3, 4, 5, 6, 7, 8, 9]
Data type : <class 'pandas.core.series.Series'>
0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

In [ ]:
# Creating a series from dictionary
a_dict = {'a':1, 'b':2, 'c':3, 'd':4, 'e':5}
print(a_dict)
# converting to series
a_dict_series = pd.Series(a_series)
print(a_dict_series)

{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}
0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

## **4.3 DataFrames**

In [ ]:
data = {
    'Student_Name': ['Anupama', 'Prasanna', 'Suraj', 'Priyanka', 'Sujit', 'Sridatta', 'Subhradip', 'Parthiv', 'Venkatesh'],
    'Roll_No': [100, 101, 102, 103, 104, 105, 106, 107, 108],
    'City': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'Y'],
    'Joining_Date': [
        '2024-06-15', '2024-07-01', '2024-07-10',
        '2024-08-05', '2024-08-20', '2024-09-01',
        '2024-09-15', '2024-10-01', '2024-10-10'
    ]
}

data

{'Student_Name': ['Anupama',
  'Prasanna',
  'Suraj',
  'Priyanka',
  'Sujit',
  'Sridatta',
  'Subhradip',
  'Parthiv',
  'Venkatesh'],
 'Roll_No': [100, 101, 102, 103, 104, 105, 106, 107, 108],
 'City': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'Y'],
 'Joining_Date': ['2024-06-15',
  '2024-07-01',
  '2024-07-10',
  '2024-08-05',
  '2024-08-20',
  '2024-09-01',
  '2024-09-15',
  '2024-10-01',
  '2024-10-10']}

In [ ]:
Data_df = pd.DataFrame(data)
Data_df

  Student_Name  Roll_No City Joining_Date
0      Anupama      100    A   2024-06-15
1     Prasanna      101    B   2024-07-01
2        Suraj      102    C   2024-07-10
3     Priyanka      103    D   2024-08-05
4        Sujit      104    E   2024-08-20
5     Sridatta      105    F   2024-09-01
6    Subhradip      106    G   2024-09-15
7      Parthiv      107    H   2024-10-01
8    Venkatesh      108    Y   2024-10-10

In [ ]:
Data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Student_Name  9 non-null      object
 1   Roll_No       9 non-null      int64
 2   City          9 non-null      object
 3   Joining_Date  9 non-null      object
dtypes: int64(1), object(3)
memory usage: 420.0+ bytes

In [ ]:
# Adding new column
Data_df['Age'] = [30,29,28,27,26,25,24,23,22]

In [ ]:
Data_df

  Student_Name  Roll_No City Joining_Date  Age
0      Anupama      100    A   2024-06-15   30
1     Prasanna      101    B   2024-07-01   29
2        Suraj      102    C   2024-07-10   28
3     Priyanka      103    D   2024-08-05   27
4        Sujit      104    E   2024-08-20   26
5     Sridatta      105    F   2024-09-01   25
6    Subhradip      106    G   2024-09-15   24
7      Parthiv      107    H   2024-10-01   23
8    Venkatesh      108    Y   2024-10-10   22

In [ ]:
Data_df.drop('Age')

KeyError: "['Age'] not found in axis"

In [ ]:
# Correct way is to mention the axis and axis here is column or row, axis = 1 is column and axis = 0 is row
Data_df.drop('Age', axis=1)

  Student_Name  Roll_No City Joining_Date
0      Anupama      100    A   2024-06-15
1     Prasanna      101    B   2024-07-01
2        Suraj      102    C   2024-07-10
3     Priyanka      103    D   2024-08-05
4        Sujit      104    E   2024-08-20
5     Sridatta      105    F   2024-09-01
6    Subhradip      106    G   2024-09-15
7      Parthiv      107    H   2024-10-01
8    Venkatesh      108    Y   2024-10-10

### **4.4 Converting date field to numerical**

In [ ]:
# Convert Joining_Date to Datetime from Object type
Data_df['Joining_Date'] = pd.to_datetime(Data_df['Joining_Date'])
Data_df['Joining_Date_number'] = (Data_df['Joining_Date'] - Data_df['Joining_Date'].min()).dt.days

In [ ]:
Data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Student_Name         9 non-null      object
 1   Roll_No              9 non-null      int64
 2   City                 9 non-null      object
 3   Joining_Date         9 non-null      datetime64[ns]
 4   Joining_Date_number  9 non-null      int64
dtypes: datetime64[ns](1), int64(2), object(2)
memory usage: 492.0+ bytes

## **4.5 Reading and performing operations on csv file**

In [ ]:
data =  pd.read_csv('/content/drive/MyDrive/Introduction to AI_2025-26/Lab_2026/Lab1/diamonds.csv')

In [ ]:
data.loc[10:20, 'carat'] = np.nan

In [ ]:
# Show first five rows
data.head(5)

   carat      cut color clarity  depth  table     x     y     z  price
0   0.23    Ideal     E     SI2   61.5   55.0  3.95  3.98  2.43    326
1   0.21  Premium     E     SI1   59.8   61.0  3.89  3.84  2.31    326
2   0.23     Good     E     VS1   56.9   65.0  4.05  4.07  2.31    327
3   0.29  Premium     I     VS2   62.4   58.0  4.20  4.23  2.63    334
4   0.31     Good     J     SI2   63.3   58.0  4.34  4.35  2.75    335

In [ ]:
# Display last 5 rows
data.tail(5)

       carat        cut color clarity  depth  table     x     y     z  price
53935   0.72      Ideal     D     SI1   60.8   57.0  5.75  5.76  3.50   2757
53936   0.72       Good     D     SI1   63.1   55.0  5.69  5.75  3.61   2757
53937   0.70  Very Good     D     SI1   62.8   60.0  5.66  5.68  3.56   2757
53938   0.86    Premium     H     SI2   61.0   58.0  6.15  6.12  3.74   2757
53939   0.75      Ideal     D     SI2   62.2   55.0  5.83  5.87  3.64   2757

In [ ]:
# Dataset shape
print(f"Shape of the dataset :{data.shape}")

Shape of the dataset :(53940, 10)

In [ ]:
# Column names and types
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   carat    53929 non-null  float64
 1   cut      53940 non-null  object
 2   color    53940 non-null  object
 3   clarity  53940 non-null  object
 4   depth    53940 non-null  float64
 5   table    53940 non-null  float64
 6   x        53940 non-null  float64
 7   y        53940 non-null  float64
 8   z        53940 non-null  float64
 9   price    53940 non-null  int64
dtypes: float64(6), int64(1), object(3)
memory usage: 4.1+ MB
None

In [ ]:
data['cut'].unique()

array(['Ideal', 'Premium', 'Good', 'Very Good', 'Fair'], dtype=object)